image: node:latest

stages:
  - build
  - deploy

Build App:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

Deploy To Test:
  stage: deploy
  when: manual
  dependencies:
    - Build App
  script:
    - eval `ssh-agent -s`
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh-add - <<< "$PROD_PRIVATE_KEY"
    - scp -P22 -r ./dist/* wishlist@wishlist.blv.ru:/var/www/admin.testwishlist.blv.ru/dist/
    - echo "All app files copied to TEST"

Deploy To Prod:
  stage: deploy
  when: manual
  dependencies:
    - Build App
  only:
    - tags
  except:
    - branches
  script:
    - eval `ssh-agent -s`
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh-add - <<< "$PROD_PRIVATE_KEY"
    - scp -P22 -r ./dist/* wishlist@wishlist.blv.ru:/var/www/admin.wishlist.blv.ru/dist/
    - echo "All app files copied to PROD"

Nightly Build:
  stage: deploy
  dependencies:
    - Build App
  only:
    - schedules
  script:
    - eval `ssh-agent -s`
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh-add - <<< "$PROD_PRIVATE_KEY"
    - scp -P22 -r ./dist/* wishlist@wishlist.blv.ru:/var/www/admin.testwishlist.blv.ru/dist/
    - echo "All app files copied to TEST"
